### PR TITLE
Document the cluster capacity framework

### PR DESCRIPTION
**Pull request by ingvagabund**

### CODE REVIEW

**Comment by ingvagabund** [comment]
@kubernetes/rh-cluster-infra

**Comment by derekwaynecarr** [comment]
I would add a section that explains what level of access the supplied kube config must have on the cluster for specific resources in order to run.   Assume you need LIST pods, etc.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **passed** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/storage/browser/cluster-capacity/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/43)

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/storage/browser/cluster-capacity/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/storage/browser/cluster-capacity/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **errored** for commit 6567cba828630eec48e646fecf9f09e629d42b9f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/10/cluster-capacity-pull-build-redhat-tests/1/index.html)

The magic incantation to run this job again is `be nice and run`.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Pull request merged**
