### PR TITLE
Rename Report to ClusterCapacityReview and refactor 

### PR DESCRIPTION
**Pull request by hodovska**
+ prepare ClusterCapacityReview to scheduling pod sequences

Issue: https://github.com/kubernetes-incubator/cluster-capacity/issues/15

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I see that this PR moves to the new type definition (which is good), but I don't see how it adds versioning semantics.  If not in this PR, can we do a follow-on that reuses the machinery from k8s to create a scheme/codec and api group for this resource and separate internal/external formats?

For reference, you could do similar to here:
https://github.com/kubernetes/kubernetes/pull/36765/commits/bed44d76ead8b43c7a64bb40c61ebbf2a1ee9eda

**Comment by aveshagarwal** [comment]
@hodovska could you update it, as it shows conflict?

**Comment by hodovska** [comment]
@aveshagarwal It should be fine now.

**Comment by ingvagabund** [comment]
Cluster capacity build/test **passed** for commit 0b1196ceda140c0c2bff4663a0519fde2ab05a3f

* [logs](https://console.cloud.google.com/m/cloudstorage/b/cluster-capacity/o/pr-logs/pull/37/cluster-capacity-pull-build-redhat-tests/1/index.html)

**Pull request merged**
