### PR TITLE
Apply go routines prs

### PR DESCRIPTION
**Pull request by ingvagabund**
This is needed to eliminate handing go-routines.

### CODE REVIEW

**Comment by hodovska** [comment]
Will test for this issue be in different PR? https://github.com/kubernetes-incubator/cluster-capacity/issues/25

**Comment by ingvagabund** [comment]
Yeap, #25 it is.

**Comment by aveshagarwal** [comment]
@ingvagabund thanks. Since we do not have any automated ci for this repo yet, could you please test before merging anything to make sure no basic functionality is broken.

**Comment by ingvagabund** [comment]
```sh
$ make integration-tests
./integration-tests.sh
####PRE-TEST CHECKS
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-18T08:05:03Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
NAME               STATUS    AGE
cluster-capacity   Active    2h


####RUNNING TESTS

# Running simple estimation of examples/pod.yaml
E0210 22:34:01.015294   32251 factory.go:583] Error scheduling cluster-capacity small-pod-26: pod (small-pod-26) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (2); retrying
The cluster can schedule 26 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-26) failed to fit in any node

# Running simple estimation of examples/pod.yaml in verbose mode
E0210 22:34:01.507486   32262 factory.go:583] Error scheduling cluster-capacity small-pod-26: pod (small-pod-26) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (2); retrying
Pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 26 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-26) failed to fit in any node
fit failure on node (2): Insufficient cpu (2)

Pod distribution among nodes:
	- kube-node-2: 13 instance(s)
	- kube-node-1: 13 instance(s)

Decrease resource in the cluster by running new pods
replicationcontroller "nginx" created
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up
waiting for pods to come up

# Running simple estimation of examples/pod.yaml in verbose mode with less resources
E0210 22:34:15.542796   32478 factory.go:583] Error scheduling cluster-capacity small-pod-23: pod (small-pod-23) failed to fit in any node
fit failure summary on nodes : Insufficient cpu (2); retrying
Pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 23 instance(s) of the pod.
Termination reason: FailedScheduling: pod (small-pod-23) failed to fit in any node
fit failure on node (2): Insufficient cpu (2)

Pod distribution among nodes:
	- kube-node-2: 12 instance(s)
	- kube-node-1: 11 instance(s)

Delete resource in the cluster by deleting rc
replicationcontroller "nginx" deleted


#### All tests passed
```

**Pull request merged**
