### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by hodovska**
Existing unit tests pass and documented functionality is also tested. 
@aveshagarwal

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@hodovska thanks. I will merge it then.

**Comment by ingvagabund** [comment]
We need to merge both https://github.com/kubernetes/kubernetes/pull/37148 and https://github.com/kubernetes/kubernetes/pull/37137 in this repository as well. Otherwise, go routines starts to leak,

**Comment by aveshagarwal** [comment]
@ingvagabund  sure we can do that.

**Comment by aveshagarwal** [comment]
@ingvagabund we already have an issue for this, https://github.com/kubernetes-incubator/cluster-capacity/issues/1 , lets discuss there.

**Pull request merged**
