### PR TITLE
cluster-capacity should only list resources needed by scheduler

### PR DESCRIPTION
**Pull request by derekwaynecarr**
the cluster-capacity command should work with same RBAC privileges as scheduler - bind.

remove resources not needed by the scheduler framework from being pulled.

### CODE REVIEW

**Comment by aveshagarwal** [comment]
thanks @derekwaynecarr, I will test it soon.

**Comment by derekwaynecarr** [comment]
I added a fakeInfomer for replica sets.  The selector spreading it offers can be achieved by adding the full set of labels to the input pod.  It also fixes an error I was getting when testing this against a kube 1.7 cluster.

```
./cluster-capacity --kubeconfig=${KUBECONFIG} --podspec=examples/pod.yaml
E0608 23:11:24.415787   11826 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode watch event: v1beta1.ReplicaSet is not suitable for converting to "v1"
24
```

I am tempted to do the same for replication controllers as well, but since its v1 and out of alpha/beta phase, I am fine leaving as is for now.  If we find simulation runs are too resource intensive though we may want to re-evalaute in future.

**Comment by aveshagarwal** [comment]
@derekwaynecarr sounds good.

**Pull request merged**
