### PR TITLE
Fix path to cc boilerplate

### PR DESCRIPTION
**Pull request by ingvagabund**
1) fixing path in the boilerplate from repo-infra ro cluster-capacity
2) running the boilerplate verification as part of the integration tests

### CODE REVIEW

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Comment by aveshagarwal** [comment]
lgtm

**Comment by ingvagabund** [comment]
Thanks guys. I will merge it tomorrow once the CI is finished. There are still some minor issues I need to fix.

**Comment by ingvagabund** [comment]
@redhat-k8s-bot test please

**Pull request merged**
