### PR TITLE
Master rebase kube 16

### PR DESCRIPTION
**Pull request by aveshagarwal**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@derekwaynecarr this is current state of cluster capacity rebase. Code compiles, but some tests are still failing. One issue I am seeing is that:

```
E0326 23:36:07.647323   15596 streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode to metav1.Event
```

**Comment by aveshagarwal** [comment]
@derekwaynecarr currently I have pushed all local changes to this PR. As I said in my one of the previous comments that I am seeing this issue:

```
streamwatcher.go:109] Unable to decode an event from the watch stream: unable to decode to metav1.Event

```
this issue is happening when you run a unit test in watch_test.go in restcclient pkg as follows:

`go test ./pkg/framework/restclient  -run TestWatchPods`

Also the same issue is happening when running cluster capacity tool as follows:

`./cluster-capacity --kubeconfig ~/.kube/config --podspec ./examples/pod.yaml`

Also current rebase is againt 1.6 rc1.

**Comment by ingvagabund** [comment]
The event struct -> json is actually constructed manually [1]. You need to construct the json the way it corresponds to the new ``metav1.Event``.

[1] https://github.com/kubernetes-incubator/cluster-capacity/blob/master/pkg/framework/watch/watch.go#L114

**Comment by aveshagarwal** [comment]
@derekwaynecarr So in the current state:

1. Code has been cleaned.
2. All tests have been fixed and are passing.
3. Internal client package has been removed.
4. All the code pretty much moved to using versioned objects.

I also tested the cluster capacity  tool against 1.6 cluster and it is working and the output is:

```
E0331 00:24:14.476018   14100 reflector.go:201] github.com/kubernetes-incubator/cluster-capacity/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/externalversions/factory.go:70: Failed to list *v1beta1.StatefulSet: Unable to process request: Resource type statefulsets not recognized
E0331 00:24:14.604001   14100 factory.go:519] Error scheduling default small-pod-26: No nodes are available that match all of the following predicates:: Insufficient cpu (1).; retrying
The cluster can schedule 26 instance(s) of the pod small-pod.

Termination reason: Unschedulable: No nodes are available that match all of the following predicates:: Insufficient cpu (1)
```

So the tool is working but  there is extra error about statefulsets. I have some patches for this locally and will test tomorrow. Other than this, I think rebase is good to go. Let me know your feedback.

**Comment by aveshagarwal** [comment]
@ingvagabund would appreciate your feedback.

**Comment by derekwaynecarr** [comment]
LGTM, i would like to get this merged asap so we can do other necessary follow-ons.

**Comment by aveshagarwal** [comment]
@derekwaynecarr thanks so do we want to wait for feedback from Jan, or lets go ahead and merge it?

**Comment by derekwaynecarr** [comment]
lets go ahead.

**Pull request merged**
