### PR TITLE
Update dependecies

### PR DESCRIPTION
**Pull request by hodovska**

### CODE REVIEW

**Comment by aveshagarwal** [comment]
@hodovska thanks. Did you do some basic/sanity testing that it does not break anything?

**Comment by hodovska** [comment]
Not yet, I'll run all existing tests and manually test functionality. I'll let you know when I am finished. Do we have do-not-merge label?

**Comment by aveshagarwal** [comment]
@hodovska  Thanks. Though I dont see do-not-merge label in the list, think dont worry about the label as we are the ones going to merge it.

**Comment by aveshagarwal** [comment]
@hodovska Unless I am missing something, I see that you are directly creating branches in this repo? I see a new branch update-kube. I would suggest that you just follow the normal process that means fork this repo and create a branch in your forked repo and then create PRs here.

**Pull request closed without merging**
