### PR TITLE
Master changes for release

### PR DESCRIPTION
**Pull request by aveshagarwal**
@derekwaynecarr @ingvagabund 

Fixes https://github.com/kubernetes-incubator/cluster-capacity/issues/68

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I love the ratio of new code to old code in this PR.

LGTM to merge for now.

**Comment by aveshagarwal** [comment]
>I love the ratio of new code to old code in this PR.

:+1: 

I am going to add a few more commits today , will update soon.

**Comment by aveshagarwal** [comment]
Built and tested cluster capacity container image with local kube cluster as follows:
```
docker run -it --net=host -v ~/.kube/config:/root/config:z  -v /root/upstream-code/gocode/src/github.com/kubernetes-incubator/cluster-capacity/examples:/examples:Z -v /var/run/kubernetes:/var/run/kubernetes:Z ccimage /bin/bash -c '/bin/cluster-capacity --kubeconfig /root/config --podspec /examples/pod.yaml --default-config /config/default-scheduler.yaml'
```

**Comment by aveshagarwal** [comment]
@derekwaynecarr the last 3 commits now have support for incluster config and I tested it in a pod and it works. Please let me know if you have any feedback about it.

As far as I understand one issue left is the error thrown by the scheduler. Due to this error, the pod is going into crashloopbackoff. If it were to be run once in a pod, it could be configured with no restart on failure. But running as a job, it seems an issue. I am still looking how to handle it. Let me know if you have thoughts.

**Comment by aveshagarwal** [comment]
Also, right now It needs `CC_INCLUSTER` env variable to be set to true as part of pod specification to make cluster capacity aware that it is going to run in a pod.

**Comment by derekwaynecarr** [comment]
LGTM, lets merge this.

**Pull request merged**
