### PR TITLE
Remove unused Java import package

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
dummy comment to try to update the CLA

**Comment by apupier** [comment]
seems to be upstream, i created https://github.com/kubernetes/examples/pull/142

**Comment by apupier** [comment]
fixed upstream, what needs to be done to have it fixed here?

**Comment by aveshagarwal** [comment]
@apupier once we update/rebase this repo next time, it will pick up the latest changes in kuberenetes/example repo.

**Comment by apupier** [comment]
then i can close this PR?

**Comment by apupier** [comment]
> once we update/rebase this repo next time

how often is it done?

**Comment by aveshagarwal** [comment]
> then i can close this PR?

yes.

> how often is it done?

less often to maintain stability, but since its been a while, we will do it sooner than later.

**Pull request closed without merging**
