### PR TITLE
Bump to k8s 1.15.3

### PR DESCRIPTION
**Pull request by ingvagabund**
Also:
- migrate to dep (still too early for go modules since the scheduling code is not fully migrated under `k8s.io/kube-scheduler` [1])
- remove REST client store in favor of fake client (finally it supports watch events)
- golang version bumped to 1.12.* (based on kubernetes v1.15 release notes [2])

[1] https://github.com/kubernetes/kube-scheduler
[2] https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#other-notable-changes

### CODE REVIEW

**Comment by ingvagabund** [comment]
Running unit tests:
```sh
$ go test -v github.com/kubernetes-incubator/cluster-capacity/pkg/...
?   	github.com/kubernetes-incubator/cluster-capacity/pkg/client	[no test files]
=== RUN   TestPrediction
W0917 12:33:34.093444   29131 authentication.go:249] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0917 12:33:34.093502   29131 authentication.go:252] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0917 12:33:34.093513   29131 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0917 12:33:34.093555   29131 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
--- PASS: TestPrediction (1.64s)
    simulator_test.go:226: Reason: 0, instances: &{test-node-3 3}
    simulator_test.go:226: Reason: 1, instances: &{test-node-2 2}
    simulator_test.go:226: Reason: 2, instances: &{test-node-1 1}
    simulator_test.go:229: Stop reason: &{LimitReached Maximum number of pods simulated: 6}
PASS
ok  	github.com/kubernetes-incubator/cluster-capacity/pkg/framework	(cached)
?   	github.com/kubernetes-incubator/cluster-capacity/pkg/framework/record	[no test files]
=== RUN   TestAddPodStrategy
--- PASS: TestAddPodStrategy (0.00s)
PASS
ok  	github.com/kubernetes-incubator/cluster-capacity/pkg/framework/strategy	(cached)
?   	github.com/kubernetes-incubator/cluster-capacity/pkg/test	[no test files]
?   	github.com/kubernetes-incubator/cluster-capacity/pkg/utils	[no test files]
```

Running over real cluster:
```
$ ./cluster-capacity --kubeconfig ~/.kube/config --podspec=examples/pod.yaml --verbose
W0917 12:45:59.218036   30262 authentication.go:249] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0917 12:45:59.218117   30262 authentication.go:252] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0917 12:45:59.218151   30262 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0917 12:45:59.223902   30262 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
small-pod pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 7 instance(s) of the pod small-pod.

Termination reason: Unschedulable: 0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.

Pod distribution among nodes:
small-pod
	- ip-10-0-174-163.ec2.internal: 5 instance(s)
	- ip-10-0-159-190.ec2.internal: 2 instance(s)
```

**Comment by ingvagabund** [comment]
Also, building docker image and running the code through job manifest:
```
$ oc get jobs
NAME                   COMPLETIONS   DURATION   AGE
cluster-capacity-job   1/1           40s        20m
```

```
$ oc logs cluster-capacity-job-g6wjx
W0917 12:59:02.456707       6 authentication.go:262] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W0917 12:59:02.456869       6 authentication.go:199] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:default:cluster-capacity-sa" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W0917 12:59:02.456885       6 authentication.go:200] Continuing without authentication configuration. This may treat all requests as anonymous.
W0917 12:59:02.456898       6 authentication.go:201] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I0917 12:59:02.461434       6 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
small-pod pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 7 instance(s) of the pod small-pod.

Termination reason: Unschedulable: 0/6 nodes are available: 3 Insufficient cpu, 3 node(s) had taints that the pod didn't tolerate.

Pod distribution among nodes:
small-pod
	- ip-10-0-174-163.ec2.internal: 5 instance(s)
	- ip-10-0-159-190.ec2.internal: 2 instance(s)
```

**Comment by gramidt** [comment]
@ingvagabund - Looks great! 

LGTM!

**Comment by ingvagabund** [comment]
Running CC from within a job:

```
$ kubectl logs jobs/cluster-capacity-job
W1205 15:31:01.737624       7 authentication.go:262] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W1205 15:31:01.737996       7 authentication.go:199] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:serviceaccount:default:cluster-capacity-sa" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W1205 15:31:01.738017       7 authentication.go:200] Continuing without authentication configuration. This may treat all requests as anonymous.
W1205 15:31:01.738023       7 authentication.go:201] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I1205 15:31:01.835322       7 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
small-pod pod requirements:
	- CPU: 150m
	- Memory: 100Mi

The cluster can schedule 8 instance(s) of the pod small-pod.

Termination reason: Unschedulable: 0/1 nodes are available: 1 Insufficient cpu.

Pod distribution among nodes:
small-pod
	- minikube: 8 instance(s)
```

**Pull request merged**
