### PR TITLE
Correct the format of table in api-definitions.md

### PR DESCRIPTION
**Pull request by AdamDang**
The table FailReasons format is wrong.
need to insert a empty line below "##FailReasons"

### CODE REVIEW

**Comment by aveshagarwal** [comment]
Though I am not exactly sure what is changed. But I trust you.

/lgtm

**Comment by AdamDang** [comment]
Thanks @aveshagarwal 
After the modification, the table is OK now. before this, the table's content displays together, that means no column, all the content are put together.

**Pull request merged**
