### PR TITLE
Load current master address from kubeconfig file

### PR DESCRIPTION
**Pull request by hodovska**
Issue: https://github.com/kubernetes-incubator/cluster-capacity/issues/33

### CODE REVIEW

**Comment by derekwaynecarr** [comment]
I verified this in local testing.

**Comment by aveshagarwal** [comment]
As @derekwaynecarr has verified, I am going to merge it.

**Comment by ingvagabund** [comment]
It does not with with:
```yaml
apiVersion: v1
kind: Config
current-context: kubectl-to-cluster.local
preferences: {}
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURXVENDQWtHZ0F3SUJBZ0lKQU4zeG4zbk4ycFIvTUEwR0NTcUdTSWIzRFFFQkN3VUFNQ0l4SURBZUJnTlYKQkFNVUZ6RXdMamd1TVRjekxqRTBNa0F4TkRnM01EWXhNemMwTUI0WERURTNNREl4TkRBNE16WXhOVm9YRFRJMwpNREl4TWpBNE16WXhOVm93SWpFZ01CNEdBMVVFQXhRWE1UQXVPQzR4TnpNdU1UUXlRREUwT0Rjd05qRXpOelF3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNWZzJFQlZxL0IvdEdOajZpcGNITEwKQ2ppZ3VVd2d3MEpZdFJlRkpYTUFEd3F0dkRzdEhDMTZLaXB5WVV1WEkzbHVqd0lhbFZvSUV6S2k3eW05TXZKMQpGczJndERBRWZnWDN6TlB4MExFMElURFl3ZjNUODM2N2RBMS9ySGtscHY0TU5ac21UR3krNTUxaTZpbTltaCtlCnQzMGhPK3RtQVdBaWVNY21NdzhOWVpmMTlSU0FjS1ZpT2luZGw3NlJyWlBPbExvY1psV1ptQUM3TWFTcjVxSm8KOGpIRDArRDlSbnEydVhFUldPMlNxNnBZTTdDdTZMcEp6UUZDRDQ4STBuUUdsQlVrN0JwN0szY2U1cGNjRktNcAplb2VWdDcxRFhHQXM1R3RVeFcrcEM2THRzWGEzeVdWS0lLTzFRQzQwU3lDcDNpVVFxNTlDOExLNnZGeWhHVXFSCkFnTUJBQUdqZ1pFd2dZNHdIUVlEVlIwT0JCWUVGTEJraENvbHZnUGxSd2pvYzJpTUhpdmUyRVVoTUZJR0ExVWQKSXdSTE1FbUFGTEJraENvbHZnUGxSd2pvYzJpTUhpdmUyRVVob1Nha0pEQWlNU0F3SGdZRFZRUURGQmN4TUM0NApMakUzTXk0eE5ESkFNVFE0TnpBMk1UTTNOSUlKQU4zeG4zbk4ycFIvTUF3R0ExVWRFd1FGTUFNQkFmOHdDd1lEClZSMFBCQVFEQWdFR01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkhRRjdSY0lrTGlMSStuU2pWVStkTXcvRVcKdlZqU3hGSFNNdEVHYUpySDdheDNTZW5YQXRvVUpVNU4zVlY1eGhXV0d0cmR1Y3MxaTJrR3hBY3BuUHdNR1NZVAp0bjJEaGFzV1Z3M0RiUlJDTFM1UmV6YmNTRTh5cU1vUjNZWUJsWkR3T1VzWktGUXdXenJWOTJnbVQvV2hJdEppCnMxTkwrQlRkMjNDOCs2V1A1dXdxUG9PclJFcGxjSGlTb29udWtkMTlZQmNjY2x6eHdrSU0zd0hYc2k0d2VEVUwKNklVcHR3S2R4OW4wOUNIaWdZQTIvdW9nbXZIL1g2TUprOFRuZCs0TU53SENFVTdFZEFkVExVSjBIUlJXK01sTApjZ0J6bFYybFh6Z0F5RGZET2RITTBHRk9SNWpVN0xTV1FkcVh1NjlMbGhmUWxhQkVmaWFqdFR4Z2ppeUkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://10.8.173.142:6443
  name: cluster.local
contexts:
- context:
    cluster: cluster.local
    user: kubectl
  name: kubectl-to-cluster.local
users:
- name: kubectl
  user:
    token: tdWboaNrFPoMHXMKoFv35aBsng098ngB
```

**Comment by ingvagabund** [comment]
Thought, it works with `s/kubectl-to-cluster.local/cluster.local`.

**Comment by ingvagabund** [comment]
Got two kubeconfigs, the first generated inside cluster running in OpenStack, the other one from Vagrant box. Both have ``kubectl-to-cluster.local``.

**Comment by aveshagarwal** [comment]
@ingvagabund what errors do you get?

**Comment by ingvagabund** [comment]
"Failed to get master address from kubeconfig"

Just fixing piece of the code

**Comment by hodovska** [comment]
Yes, now I can see the mistake. We could read current context, find name of cluster in context configuration and then find server address in clusters.

Do you agree?

**Comment by ingvagabund** [comment]
Exactly

**Pull request merged**
